### ISSUE TITLE
\numberofexercise with space after

### ISSUE THREAD

**Issue by MichaelHuck** [cgnieder/xsim#101]
Just add
`There are \numberofexercises~exercises in this chapter.`
to my document. Works.

`There are \numberofexercises exercises in this chapter. `
Works not, I lose the space after the number: e.g. I get:
There are 54exercises in this chapter.
instead of
There are 54 exercises in this chapter.
I know, this is a minor issue.

Michael

**Comment by cgnieder** [comment]
This is a standard behaviour of TeX/LaTeX macros. The space terminates the macro but maybe no space in the output is wanted (e.g. the `\TeX book`). 

See also https://tex.stackexchange.com/q/31091/5049 for example.
