### ISSUE TITLE
Solutions not printed

### ISSUE THREAD

**Issue by GMS103** [cgnieder/xsim#104]
Sorry if this is a stupid question, but I am unable to solve it.
When defining a new exercise type, the solutions are not printed.
```
\documentclass{article}

\usepackage{xsim}

\xsimsetup{solution/print=true}

\DeclareExerciseType{problem}{
  exercise-env = problem ,
  solution-env = answer ,
  exercise-name = Problem ,
  solution-name = Answer ,
  exercise-template = default ,
  solution-template = default
}

\begin{document}

\begin{exercise}
  Plain exercise.
\end{exercise}
\begin{solution}
  Plain solution.
\end{solution}

\begin{problem}
  Plain problem.
\end{problem}
\begin{answer}
  Plain answer.
\end{answer}

\end{document}
```
gives
![test](https://user-images.githubusercontent.com/47718744/159140909-18c8f825-f433-4b6f-91c0-44b2f90c6e94.png)
What am I doing wrong?

**Comment by cgnieder** [comment]
You need `\xsimsetup{answer/print=true}` (of course placed _after_ the `\DeclareExerciseType` statement).

**Comment by GMS103** [comment]
That was my mistake:  I was putting `\xsimsetup{answer/print=true}` before the declaration (and getting an error).
Thanks.
