### ISSUE TITLE
Exercise-body not as tex-file

### ISSUE THREAD

**Issue by joneppie** [cgnieder/xsim#11]
We use some scripts which compile every tex-file and add the tex-file and the generated PDF-file to a website. The `*-exercise-body.tex` files create errors in this context: This `tex`-files are not a standalone document and can not compile to a pdf-File and should not be part of the website.
Is it possible to use another file extension instead of `tex`? For example, `xsim` or `xex` could be used.

**Comment by cgnieder** [comment]
That would be quite easy to implement. Actually, I'd rather add a user option which let's the user choose the extension. I'll add this to the next release (which will be published later today, anyway :) )

**Comment by cgnieder** [comment]
Implemented in cset 314ae0adbaf5a9154ed499305f821d7bf0f78c70
