### ISSUE TITLE
Usint \lstinline{#include <iostream>} display one more #

### ISSUE THREAD

**Issue by littleantgithub** [cgnieder/xsim#123]
As shown avove, I have a try  \lstinline{\#include <iostream>,}normal display. I think  there might be a bug here.

**Comment by littleantgithub** [comment]
![2023-12-26_16-04](https://github.com/cgnieder/xsim/assets/68120589/172d52f8-bfb4-4e78-9a8f-a085dd2635dd)
![2023-12-26_16-04_1](https://github.com/cgnieder/xsim/assets/68120589/414ace84-bf51-45ed-a5f0-f000368ef58e)
![2023-12-26_16-05](https://github.com/cgnieder/xsim/assets/68120589/02c87820-e274-4d14-afba-5258845bf5c7)
I have not used md, sorry, the text is not fully displayed.

**Comment by muzimuzhi** [comment]
Not reproducible. Please provide a [minimal working example](https://tex.meta.stackexchange.com/q/228).

In principle, you need `xsim`'s `use-files` package option to use arbitrary verbatim material in exercise and solution environments.

```tex
\documentclass{article}
\usepackage{xsim}
\usepackage{listings}

\lstset{basicstyle=\ttfamily}

\begin{document}
xxx \lstinline{abc} xxx

xx \lstinline{#include} xxx

xx \lstinline{\#include} xxx

\textsf{xxx \lstinline{abc} xxx}

\textsf{xxx \lstinline{#include} xxx}

\textsf{xxx \lstinline{\#include} xxx}

\begin{exercise}
  xxx \lstinline{abc} xxx

  xx \lstinline{#include} xxx

  xx \lstinline{\#include} xxx
\end{exercise}
\end{document}
```

![image](https://github.com/cgnieder/xsim/assets/6376638/ca027dc2-ed66-4c05-985c-d7c8d267c2d4)

> I have not used md, sorry, the text is not fully displayed.

You can edit your first comment to use markdown inline code span (`` `code` ``) or fenced code blocks (which will look like the above full latex example I give), see related [GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by littleantgithub** [comment]
```
\documentclass{article}
\usepackage{xsim}
\usepackage{listings}
\usepackage{xeCJKfntef}
\usepackage{fontspec}
\begin{document}
\lstinline{#include<iostream> }
\begin{exercise}
  \lstinline{#include<iostream> }
\end{exercise}
\end{document}
```

I apologize for not providing all the required information.. I think the above code is the minimum trigger condition.
Just in case, the following is relatively complete.
```
...
  \usepackage[10pt,UTF8, heading=true]{ctex}
  \usepackage[dvipsnames, svgnames, x11names]{xcolor}  % 一般放得靠前
  \usepackage{geometry}
  \geometry{left=2cm, right=2.0cm,top=2.0cm, bottom=2cm}
  \usepackage{subfiles}
  \usepackage{caption}
  \usepackage{hyperref}
  \usepackage{graphicx}
  \usepackage[inkscapelatex=false]{svg}
  \usepackage{wrapfig}
  \usepackage{xsim}
  \usepackage{listings}
  \usepackage{tcolorbox}
  \usepackage{xeCJKfntef}
  \usepackage{fontspec}
  \setmainfont{Source Code Pro}
  %\setCJKmainfont{WenQuanYi Zen Hei Mono}
  %\usepackage[printsolution=true]{exercises}
...
```
...
```
\documentclass{article}
\usepackage{xeCJKfntef}
\usepackage{fontspec}
\usepackage{xsim}
\usepackage{listings}

\lstset{basicstyle=\ttfamily}

\begin{document}
xxx \lstinline{abc} xxx

xx \lstinline{#include} xxx

xx \lstinline{\#include} xxx

xxx \lstinline{abc} xxx

xxx \lstinline{#include} xxx

xxx \lstinline{\#include} xxx

\begin{exercise}
  xxx \lstinline{abc} xxx

  xx \lstinline{#include} xxx

  xx \lstinline{\#include} xxx
\end{exercise}
\end{document}
```

![2023-12-26_18-43](https://github.com/cgnieder/xsim/assets/68120589/46ed9553-a8e3-4687-a352-3466e7387757)

**Comment by muzimuzhi** [comment]
It's a `xeCJK` issue (which is loaded by `xeCJKfntef`), see https://github.com/CTeX-org/ctex-kit/issues/378.
