### ISSUE TITLE
Custom Exercise-Type: Solutionbody not printed

### ISSUE THREAD

**Issue by mspee** [cgnieder/xsim#13]
Hello,

I am using two exercise types, the generic exercise and a custom defined one. 
Both are using the same template for the exercise and the solution part.

The main function of my exercise-template: 
Printing the question, leaving empty space below if solution exists AND solution/print is false or alternatively using the same space to show the solution in tcolorbox.

This works perfectly for the exercise-environment. However, in the self-defined question environment this does not work. The template produces empty spaces and the headings are correct, but the body of the solution is not printed. It seems like `\IfInsideSolutionTF` is not detecting the solution environment.

MWE:
```
\documentclass[]{article}
\usepackage{lipsum,tcolorbox,needspace,xsim}

% XSIM Settings
\xsimsetup{
	path=cache,
	file-extension=aux,
	blank/blank-style={#1},
	blank/filled-style=\textcolor{blue}{#1},
	blank/line-minimum-length=2cm,
	solution/print=true
}

\SetExerciseParameters{exercise}{
	exercise-name = \XSIMtranslate{exercise},
	exercise-template = exercise,
	solution-template = exercise,
	counter = section,
	counter-within = chapter
}

\DeclareExerciseType{question}{
	exercise-env = question,
	solution-env = answer,
	exercise-name = \XSIMtranslate{question},
	solution-name = \XSIMtranslate{solution},
	exercise-template = exercise,
	solution-template = exercise
}

\newlength{\defaultsolutionspace}
\setlength{\defaultsolutionspace}{2cm}
\newlength{\solutionspace}
\setlength{\solutionspace}{\defaultsolutionspace}
\DeclareExerciseProperty{solutionspace}

\DeclareExerciseEnvironmentTemplate{exercise}{%
	\IfExercisePropertySetTF{solutionspace}{
		\setlength{\solutionspace}{\GetExerciseProperty{solutionspace}}
	}{\setlength{\solutionspace}{\defaultsolutionspace}}
	\IfInsideSolutionTF{
		\tcolorbox[
		detach title,
		title 		 = \XSIMtranslate{solution},
		before upper = {\tcbtitle\par} ,
		fonttitle	 = \bfseries,
		fontupper    = \normalsize,
		valign       = top,
		colframe     = black!20!white,
		colback      = black!3!white,
		coltext      = black,
		coltitle     = black,
		height       = \solutionspace,
		boxrule	     = 0.5pt,
		width        = \linewidth,
		left		 = 2mm,
		sharp corners
		]
	}{
		\needspace{\solutionspace}
		\subsection*{%
			\XSIMmixedcase{\GetExerciseName}~\GetExerciseProperty{counter}
			\GetExercisePropertyT{subtitle}{~\normalfont\itshape\PropertyValue}%
			\GetExercisePropertyT{points}{~\normalfont(\PropertyValue~P)}
			\GetExercisePropertyT{ID}{\label{ex:\PropertyValue}}
		}
	}
}{	
	\IfInsideSolutionTF{\endtcolorbox}{
		% fill out template
		\IfSolutionPrintF{
			\IfExistSolutionT{
				\tcolorbox[
				detach title,
				fonttitle	 = \bfseries,
				fontupper    = \normalsize,
				valign       = top,
				colframe     = white,
				colback      = white,
				coltext      = blue,
				coltitle     = black,
				height       = \solutionspace,
				boxrule	     = 0.5pt,
				width        = \linewidth,
				left		 = 2mm,
				sharp corners
				]
				\endtcolorbox
			}
		}
	}
}

\begin{document}

\begin{question}[points=2,solutionspace=3cm]
	\lipsum[2]
\end{question}

\begin{answer}
	\lipsum[2]
\end{answer}

\begin{exercise}[points=2,solutionspace=5cm]
	\lipsum[2]
\end{exercise}

\begin{solution}
	\lipsum[2]
\end{solution}

\end{document}
```

Any ideas?

**Comment by cgnieder** [comment]
Can you please make this into a [MWE](https://tex.meta.stackexchange.com/questions/228/)?

**Comment by cgnieder** [comment]
I get this result from your MWE ([test.pdf](https://github.com/cgnieder/xsim/files/1340275/test.pdf)):

![grafik](https://user-images.githubusercontent.com/2248538/30959113-79ad3dc4-a43f-11e7-9e5f-de2669ca66bb.png)

What should it look like?

**Comment by mspee** [comment]
It should also print the solution of the answer-environment from the exercise-type "question".
Am I making some stupid mistake 🤦‍?

**Comment by cgnieder** [comment]
You didn't tell `xsim` to print `answer`s.
```latex
% XSIM Settings
\xsimsetup{
	...
	solution/print=true
}
```

You also need to set `answer/print=true` (*after* defining the new exercise type). 

(The result will then look strange but that is probably an issue with the definition of the `exercise` template).

**Comment by mspee** [comment]
Thank you so much, I feel dumb! The results looks perfect now. The template is used to leave space below every exercise for the students to fill in their solution. The sample solution however should have the exact same layout and print the solution-text in the grey boxes.
