### ISSUE TITLE
Create exercise directory automatically

### ISSUE THREAD

**Issue by ChristopherChudzicki** [cgnieder/xsim#14]
I generally use 

```
\xsimsetup{
	path=xsim-temp
}
```

so that `xsim` writes its files to a subdirectory. 

Would it be possible for `xsim` to automatically create such directories?

And of course: Thanks for this package. I'm really excited about using `verbatim` and `pythontex` environments directly in the exercises.

**Comment by cgnieder** [comment]
That is not easily possible in general: this would require me to have write access so you'd need to compile with `shell-escape`. Then creating directories is different on different OSs… I'd rather have users make this on their own.
That being said I think it should be possible to use [`arara`](https://github.com/cereda/arara) for this…

**Comment by ChristopherChudzicki** [comment]
That makes sense. I haven't used `arara` but it looks interesting. I've been using `latexmk` through my text editor. I don't have a lot of experience with it, but I might first try to edit the `latexmk` clean routine to delete the temp files.
