### ISSUE TITLE
xsim and beamer

### ISSUE THREAD

**Issue by romildo** [cgnieder/xsim#17]
`xsim` is not compatible to `beamer`. Both packages defines the environment `solution`. But even after undefinind the `beamer` one, there are issues:

``` latex
\documentclass{beamer}

% Beamer already has a solution environment which will be renamed here
\makeatletter
\@ifclassloaded{beamer}{%
  %%% save beamer's `solution' environment as `beamersolution':
  \let\beamersolution\solution
  \let\endbeamersolution\endsolution
  %%% "delete" the `solution' environment:
  \let\solution\relax
  \let\endsolution\relax
}{%
}%
\makeatother

\usepackage[verbose]{xsim}

\begin{document}

\begin{frame}
  \frametitle{Testing \emph{xsim}}
  \begin{itemize}
    \item First item.
    \item An exercise:
    \begin{exercise}
      This is an exercise.
    \end{exercise}
  \end{itemize}
\end{frame}

\end{document}
```
Compilation:
```
$ pdflatex xsim-beamer.tex 
[...]
No file xsim-beamer.nav.
(/alt/texlive/2017-NixOS/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/alt/texlive/2017-NixOS/texmf-dist/tex/latex/amsfonts/umsb.fd)
! Missing number, treated as zero.
<to be read again> 
                   \c@paragraph 
l.29 \end{frame}
                
? 
```

Please, make `xsim` usable with `beamer`.

**Comment by cgnieder** [comment]
Add `\newcounter{paragraph}` and use `\begin{frame}[fragile] ... \end{frame}`.

I must say I am quite surprised by this use of `xsim`. It aims at creating exercise sheets or exercises with solutions in books, maybe also for creating exams. But I never anticipated that it might be used in presentations… o.O

**Comment by romildo** [comment]
I would like to use `xsim` to write slides for programming classes with practices, where I intersperse explanatory material, examples, and tasks (exercises).

**Comment by benoitldr** [comment]
hello,
I have the same issue any solution ?
thanks you

**Comment by ptoche** [comment]
just for your information Clemens, my use case is an in-class test where the questions are projected on screen and not printed on paper: Since I have an extended database of questions, it makes sense to use `xsim`. And while it would be reasonably easy to use the article class with a custom geometry to mimic the effect of `beamer`, well it's natural to want to use beamer. :-)

**Comment by 135Sky** [comment]
Just add \newcounter{paragraph} with what you do @romildo .
You need to defined a new \DeclareExerciseType to have the headings. (There is a good one with tcolorbox).

MWE :
```
\documentclass[12pt,aspectratio=1610]{beamer}%Information to be included in the title page:
\makeatletter
\@ifclassloaded{beamer}{%
  %%% save beamer's `solution' environment as `beamersolution':
  \let\beamersolution\solution
  \let\endbeamersolution\endsolution
  %%% "delete" the `solution' environment:
  \let\solution\relax
  \let\endsolution\relax
}{%
}%
\makeatother
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage{xsim}
\newcounter{paragraph}

\DeclareExerciseType{test}{
	exercise-env = question ,
	solution-env = answer ,
	exercise-name	= Ex. ,
	exercises-name = Ex. ,
	solution-name = Sol. ,
	solutions-name = Sol. ,
	exercise-template = default ,
	solution-template = default ,
	exercise-heading = \textbf ,
	solution-heading = \textbf
}

\begin{document}
	\begin{frame}
		\begin{question}
			Test
		\end{question}
		\begin{answer}[print=true]
			Answer
		\end{answer}
	\end{frame}
\end{document}
```
