### ISSUE TITLE
Error when subtitle contains absolute value ("pipe")

### ISSUE THREAD

**Issue by ChristopherChudzicki** [cgnieder/xsim#18]
I'm getting an error when I compile documents where an exercise subtitle contains the pipe `|` character. Here's a MWE:

```latex
% test.tex
\documentclass{article}

\usepackage{xsim}

\begin{document}

\begin{exercise}[subtitle={$|w|$}]
    Hello, world!
\end{exercise}

\end{document}
```

When I run `pdflatex test.tex` twice, the second run throws an error:

```
Runaway argument?
$\q_stop \tl_set_rescan:Nnx \l__xsim_tmpc_tl {}{\l__xsim_tmpc_str }\__xsim_set_
property:VVnV \ETC.
! File ended while scanning use of \__xsim_extract_property_list_entry:NNNwww.
<inserted text> 
                \par 
<*> test.tex
```

(Although, looking at the generated PDF, the document appears OK. But it makes me nervous.)

**Comment by cgnieder** [comment]
Hi, thanks. This is not really a bug but should be resolved nonetheless. The problem stems from this. If you have several exercises

```latex
\documentclass{article}

\usepackage{xsim}

\begin{document}

\begin{exercise}[subtitle=foo]
  Hello, world!
\end{exercise}
\begin{exercise}[subtitle=bar]
  Hello, world!
\end{exercise}

\end{document}
```

then you'll find in the aux file lots of lines like this one

```latex
\XSIM {subtitle}{exercise-1=={foo}|exercise-2=={bar}}
```

where the `|` character is used to separate entries. I'll implement an option so that you'd be able to say

```latex
\documentclass{article}

\usepackage{xsim}
\xsimsetup{
  split-aux-lists = ||
}
\begin{document}

\begin{exercise}[subtitle={$|w|$}]
  Hello, world!
\end{exercise}
\begin{exercise}[subtitle=bar]
  Hello, world!
\end{exercise}

\end{document}
```

**Comment by cgnieder** [comment]
I will also make `||` the default so hopefully most people will not have to worry about this…
I wonder why you are using `|` in the first place. From what it looks like I would probably use something like

```latex
\usepackage{mathtools}
\DeclarePairedDelimiter\abs{\lvert}{\rvert}
```

and

```latex
\begin{exercise}[subtitle={$\abs{w}$}]
```

**Comment by cgnieder** [comment]
This is included in v0.11:

```latex
\documentclass{article}

\usepackage{xsim}
\xsimsetup{
  split-aux-lists = ||
}
\begin{document}

\begin{exercise}[subtitle={$|w|$}]
  Hello, world!
\end{exercise}
\begin{exercise}[subtitle=bar]
  Hello, world!
\end{exercise}

\end{document}
```

**Comment by ttnick** [comment]
I considered opening a new issue but I think this one is closely enough related. A colleague of mine encountered the following error (`xsim v0.20c`, TeX Live 2022):
`File ended while scanning use of \__xsim_extract_property_list_entry:NNNwww.`
on *every second* run of `pdflatex`, when he uses `||` within an exercise or solution environment. I believe this is essentially the same issue as the original one here that a `||` causes `xsim` to confuse it for a separator in the `*.xsim` file.
MWE:
```latex
\documentclass[a4paper,12pt]{article}
\usepackage{xsim}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}

\begin{document}
\begin{exercise}
	Consider the following set
	\[
		B(c, r) = \{x \in \mathbb{R}^n \mid ||x - c||_2 \leq r\}.
	\]
\end{exercise}
\end{document}
```
I told him that that use of `||` is not good anyway but the error seems strange enough that I thought I report it to you. 
(If that matters, there is also notation from scheduling theory that might create the double pipe, e.g. `P||C_\max` is short for the scheduling problem with multiple machines that wants to minimize the makespan.)

**Comment by muzimuzhi** [comment]
@ttnick I would suggest to use either `\|` or `\Vert` to typeset double vertical bar. For the problem with `||`, see #109.
