### ISSUE TITLE
loadxsimstyle failed with v0.11

### ISSUE THREAD

**Issue by joneppie** [cgnieder/xsim#19]
With ```\loadxsimstyle{schule-default}``` and file named ```xsim.style.schule-default.code.tex``` (Manual page 49) I get:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! xsim error: "module-missing"
! 
! You've requested the xsim module `schule-default' but it appears to be
! missing on your system. Maybe you've misspelled the name? Loading the module
! will abort on line 59
! 
! See the xsim documentation for further information.
! 
! Type <return> to continue.
!...............................................  
                                                  
l.59 \loadxsimstyle{schule-default}
```

If file named ```xsim.schule-default.code.tex``` (until v0.10), I get:
```
! Argument of \ProvidesFile has an extra }.
<inserted text> 
                \par 
l.3 \xsimstyle{schule-default}
```

**Comment by cgnieder** [comment]
Yes, this is a documented change, see section B.7 pager 49 of the manual to v0.11. You need to call the file `xsim.style.schule-default.code.tex`

**Comment by joneppie** [comment]
I get the first error with the name ```xsim.style.schule-default.code.tex```, so I think there is a bug in the code.

**Comment by cgnieder** [comment]
I rather suspect you incorrectly installed v0.11. The manual loads the style `layouts` (which comes with the package) and if there were a problem I wouldn't have been able to compile the manual without errors. Place `\listfiles` at the beginning of your MWE and check in the log which package files are used.
