### ISSUE TITLE
How to activate predefined layouts runin or margin?

### ISSUE THREAD

**Issue by kamar535** [cgnieder/xsim#20]
I've previously used the `exsheets` package and now want to migrate to `xsim`. I've installed The [MacTeX-2017 Distribution](http://www.tug.org/mactex/) which comes with `xsim`. According to my `.log` file I'm using version `0.8a` of `xsim` and I note that the latest version of `xsim` is `0.11`.

**Note:** It may be that my problem goes away if I manage to upgrade `xsim` to version `0.11`, something I'm currently don't know how to do.  

From the `xsim` manual section 13.2 Templates Provided by the Package:

* the following three predefined layouts are mentioned: `default`, `runin` and `margin`.
* the `runin` and `margin` layouts are "Available through the style file layouts". 

How do I activate the `runin` or `margin` layouts?  

I've found the definitions of `runin` and `margin` in [xsim.style.layouts.code.tex](https://github.com/cgnieder/xsim/blob/master/code/xsim.style.layouts.code.tex)

If I try: 

```
\loadxsimstyle{runin}
```

, I get the following error.

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! xsim error: "module-missing"
!
! You've requested the xsim module `runin' but it appears to be missing on
! your system. Maybe you've misspelled the name? Loading the module will abort
! on line 5
!
! See the xsim documentation for further information.
!
! Type <return> to continue.
!...............................................

l.5 \loadxsimstyle{runin}
```

Do I have to manually create the style files or inline the  template definitions listed in the following sections?

* 13.5.3. Mimicking exsheets’ runin Template
* 13.5.4. Mimicking exsheets’ margin Template

Or, do I need to upgrade to `xsim` version `0.11`?

**Comment by kamar535** [comment]
I've now used the TeX Live utility to update `xsim 0.10` which is still one minor version behind the latest `0.11`. Same results as before.

**Comment by kamar535** [comment]
Aha, after finding out that `runin` and `margin` are both defined in  [xsim.style.layouts.code.tex](https://github.com/cgnieder/xsim/blob/master/code/xsim.style.layouts.code.tex) I should have realised that I needed to do: 

```
\loadxsimstyle{layouts} 
```

Next, use `\xsimsetup` to select templates for both exercises and solutions. 

```
\xsimsetup{
  exercise/template = margin,
  solution/template = margin
}
```

Maybe this could be made more explicit in the manual or maybe I'm used easily confused 😃

**Comment by cgnieder** [comment]
Hi. You are right, this isn't very obvious from the manual.

Still I'm glad you figured out the solution.
