### ISSUE TITLE
xsimverb causes problems if it is used standalone

### ISSUE THREAD

**Issue by wunderlich** [cgnieder/xsim#21]
I can't use `xsimverb` standalone anymore. The example 3 (*code-and-output*) also doen't work anymore:

`! Undefined control sequence.<argument> \g_xsim_final_bool \begin{example}`

Using `\usepackage{xsim}` (instead of `\usepackage{xsimverb}`) causes no error.

**Comment by cgnieder** [comment]
At least with the current development version I cannot reproduce this issue. I will send an update to CTAN in a few days…
