### ISSUE TITLE
Specifying a Hidden Folder as a Path

### ISSUE THREAD

**Issue by aubertc** [cgnieder/xsim#22]
Trying to give a hidden folder (i.e., a folder whose name starts with a `.` on Linux systems) as a "path" results in error. I.e., even if the folder ".cache" exists, the following won't compile:

```
\documentclass{article}
\usepackage{xsim}
\xsimsetup{path = {.cache}}

\begin{document}
\begin{exercise}
	Hello
\end{exercise}
\end{document}
```

While, of course, having the folder named "cache" (without the dot) and setting the path accordingly would work.

Is that a feature? A bug? I think it would be convenient to be able to store the aux files in a hidden file.

**Comment by cgnieder** [comment]
That is not `xsim`'s fault. Assuming you're using TeX Live on a linux OS then it is set up to disallow writing to dot files or parent directories. This is controlled by the value of `open_any` in `texmf.cnf`, see for example https://tex.stackexchange.com/q/198629/

**Comment by aubertc** [comment]
Ok, thanks.

I guess I was confused by the fact that it is possible to have store the cache files of `minted` in a hidden folder.
It probably is because `minted` uses the `--shell-escape` option, hence bypassing this security measure.
