### ISSUE TITLE
Tips as a further option in addition to tasks and solutions

### ISSUE THREAD

**Issue by joneppie** [cgnieder/xsim#23]
In some contexts we have included in the [schule package](https://www.ctan.org/pkg/schule) not only exercises and solutions but also tips on the exercises. This is used for example at [http://ddi.uni-wuppertal.de/material/materialsammlung/oberstufe/automaten/leitprogramm_automaten.pdf](http://ddi.uni-wuppertal.de/material/materialsammlung/oberstufe/automaten/leitprogramm_automaten.pdf).
We want to have this in the new version of the schule package, which now fully relies on xsim. It would be possible to integrate these tips directly into the schule package. But I see it more in xsim. I would therefore also offer to support this enlargement.

**Comment by cgnieder** [comment]
Have you seen the “hints” example in the manual (section F example 9)?

 - Source file: https://github.com/cgnieder/xsim/blob/master/doc/examples/xsim.hints.tex
 - PDF: https://github.com/cgnieder/xsim/blob/master/doc/examples/xsim.hints.pdf

**Comment by cgnieder** [comment]
One of the ideas of `xsim` I had in mind is that users create their own style files. In these style files definitions can reside that define things like tips or hints. It sounds perfectly reasonable to me that a package might contain such a style file file and load it.

**Comment by cgnieder** [comment]
Does the *hint* example suit your needs or do you want me to add something to `xsim`?

**Comment by joneppie** [comment]
I am currently testing different scenarios with the hint example. If it is not enough, I will create a new issue and refer to this issue.
