### ISSUE TITLE
setting rules with \IfInsideSolutionF conditional

### ISSUE THREAD

**Issue by ptoche** [cgnieder/xsim#26]
More like a limitation. The following worked:

```latex
\newcommand*{\mytoprule}{\IfInsideSolutionF{0pt}\IfInsideSolutionT{2pt}} 
\DeclareExerciseEnvironmentTemplate{tcb}{toprule = \mytoprule}
```

but the following resulted in ``! Missing = inserted for \ifdim.`` error:

```latex
\DeclareExerciseEnvironmentTemplate{tcb}{toprule = \IfInsideSolutionF{0pt}\IfInsideSolutionT{2pt}}
```

I expected the above to work because the following does work:

```latex
\DeclareExerciseEnvironmentTemplate{tcb}{coltext = \IfInsideSolutionF{black}\IfInsideSolutionT{red}}
```

It seems that all the ``color`` options work with that construct, while the ``rule`` options fail (``boxrule``, ``titlerule``, etc).

**Comment by cgnieder** [comment]
Try

```latex
\DeclareExerciseEnvironmentTemplate{tcb}{\IfInsideSolutionT{toprule = 2pt}}
```

**Comment by ptoche** [comment]
Thanks for the suggestion. I forgot to say that I had tried that. The error message is:

    Package pgfkeys Error: I do not know the key '/tcb/boxrule = 2pt' and I am going to ignore it. Perhaps you misspelled it.

**Comment by cgnieder** [comment]
Then please post a [MWE](https://tex.meta.stackexchange.com/q/228/) (with focus on the *minimal*) I can test with. Otherwise I'll just close this issue.

**Comment by ptoche** [comment]
I made a MWE, but then the problem did not occur! So I'll need to investigate further to identify which combination of packages/template options lead to the problem. I may need a few days to debug. Thanks for your patience.

MWE below does NOT exhibit the problem I have with the non-MWE template I use.

    \documentclass{article}
    \usepackage{xsim}
    \usepackage[most]{tcolorbox}
    
    \DeclareExerciseEnvironmentTemplate{mwe}
        {\tcolorbox[%
            boxrule = \IfInsideSolutionF{0pt}\IfInsideSolutionT{2pt},
            coltext = \IfInsideSolutionF{blue}\IfInsideSolutionT{red}
    ]}{\endtcolorbox}
    
    \xsimsetup{%
        exercise/template = mwe, 
        solution/template = mwe,
        solution/print = true}
    
    \begin{document}
    
    \begin{exercise}
    Exercise text here
    \end{exercise}
    
    \begin{solution}
    Solution of exercise here
    \end{solution}
    
    \end{document}

**Comment by ptoche** [comment]
Please close this! I can no longer reproduce the problem I had. I have no idea what happened. The closest I can get to something odd is by inserting a space between the two commands in the MWE above, e.g. 

    \IfInsideSolutionF{blue} \IfInsideSolutionT{red}

which gives:

    ! Package xcolor Error: Undefined color `blue '.

I had no space between the commands, so something else was going on, but the fact that in the MWE above it is sufficient to insert a blank space to mess things up suggests that I may very well have had some space issue somewhere. 

Apologies for the bother with this clearly "too localized" issue.  Please close.
