### ISSUE TITLE
Counting points from random exercises

### ISSUE THREAD

**Issue by cgnieder** [cgnieder/xsim#27]
```latex
\documentclass{article}
\usepackage{xsim}

\DeclareExerciseCollection{foo}

\usepackage{filecontents,lipsum}
\begin{filecontents*}{foo.tex}
\begin{exercise}[points=1]
  foo one \lipsum[4]
\end{exercise}
\begin{solution}
  foo one \lipsum[4]
\end{solution}
\begin{exercise}[points=2]
  foo two \lipsum[4]
\end{exercise}
\begin{solution}
  foo two \lipsum[4]
\end{solution}
\begin{exercise}[points=3]
  foo three \lipsum[4]
\end{exercise}
\begin{solution}
  foo three \lipsum[4]
\end{solution}
\end{filecontents*}

\begin{document}

\collectexercises{foo}
\input{foo.tex}
\collectexercisesstop{foo}

\printrandomexercises[collection=foo]{1}

% prints 6 instead of either 1, 2, or 3:
Total: \printtotalpoints

\end{document}```

**Comment by ptoche** [comment]
This may be related to the issue I reported here: https://tex.stackexchange.com/questions/419046/xsim-incorrect-number-of-questions-and-total-of-points

(I reported the issue on tex.stackexchange  assuming that I was doing something wrong, not realizing it might be a bug)

**Comment by ptoche** [comment]
@cgnieder , Clemens, let me know if you'd like me to close that stackexchange question. I'm leaving it for now as it has a screenshot, I'm not sure I'd know how to insert a screenshot in here.

**Comment by TorbjornT** [comment]
@ptoche Slightly off-topic, but anyways: to insert a screenshot here, first copy it by right clicking on it -> Copy image. Then simply hit Ctrl + V in the text box here, and the image is uploaded and added to your post.

**Comment by ptoche** [comment]
@TorbjornT, Thanks, I didn't realize that. And I was actually able to copy-paste the entire post from stackexchange, so will close my question there.
