### ISSUE TITLE
Feature request: an option for not defining the default environments

### ISSUE THREAD

**Issue by ptoche** [cgnieder/xsim#31]
As can be seen from my question [here](https://tex.stackexchange.com/questions/428153/xsim-question-solution-throws-environment-already-defined/428168?noredirect=1#comment1071763_428168), I inadvertently attempted to redefine the ``solution`` environment and got an error for it. An immediate workaround was to use other words, such as ``solutions`` (with an s), ``hints``, ``discussion``, ``answer``. But since I was not using the default ``exercise`` environment with its ``solution`` environment, it seemed like a shame to have that most venerable word wasted. So I'm wondering if it would be possible to have an option to not load the default environments, such that the keywords ``solution`` and related could be used for customized environments. 

And before signing off, a big cheers for a wonderful package.

**Comment by cgnieder** [comment]
This seems like a valid request. I'll try to come up with a solution that doesn't break the current behaviour
