### ISSUE TITLE
What is the meaning of <hooks>? How to use them?

### ISSUE THREAD

**Issue by GardnerZhao** [cgnieder/xsim#35]
What does the mean of <hooks>?There are eight commands in all. I do not understand them. And who can tell me how to use these eight commands and give me some examples of these eight commands.
Thanks.
```
1.  exercise/pre-hook={code},     (initially empty）
2.  exercise/begin-hook={code},    (initially empty）
3.  exercise/end-hook={code},   (initially empty）
4.  exercise/post-hook={code},   (initially empty）
5.  solution/pre-hook={code},    (initially empty）
6.  solution/begin-hook={code},    (initially empty）
7.  solution/end-hook={code},   (initially empty）
8.  solution/post-hook={code},   (initially empty）
```

**Comment by cgnieder** [comment]
Maybe you don't ever need them. They can be useful if you don't want to define a whole new environment template for your exercises but only want to add small modifications. Here is a real world example on a German Q&A site where the hooks were useful:

[xsim printcollection - Jede Aufgabe mit Lösung auf einer neuen Seite](https://texwelt.de/wissen/fragen/22255/)

**Comment by GardnerZhao** [comment]
I'm very excited to receive your reply. I will study your it carefully. In addition, thank you very much for developing such a great macro package. As a middle school math teacher, I am deeply in love with xsim.
thx.
