### ISSUE TITLE
What is the meaning of <addto*goal>? How to use?

### ISSUE THREAD

**Issue by GardnerZhao** [cgnieder/xsim#36]
What does the mean of <addto*goal>s  in the section 7 on page 14 of the Manual ? There are four commands in all . I tried a lot of things, but they all went wrong . I can't figure out where to put them ? And how to use these  commands ? Do you need to match other commands ? Please give me some examples of these eight commands .
Thanks a lot .
This is my MWE.
```
\documentclass{article}
\usepackage{xsim}

\begin{document}

\begin{exercise}[points=1]
First.
\end{exercise}

\begin{exercise}[points=2]
Second.
\end{exercise}

\begin{exercise}[points=3]
Third.
\end{exercise}

%\AddtoExerciseGoal{points}{2}
%\AddtoExerciseTypeGoal{exercise}{points}{3}
%\AddtoExerciseTypeGoalPrint{points}{4}{\,\XSIMtranslate{point}}{\,\XSIMtranslate{points}}
%\AddtoExerciseTypeGoalPrint{exercise}{points}{5}{\,\XSIMtranslate{point}}{\,\XSIMtranslate{points}}
\end{document}
```

**Comment by cgnieder** [comment]
> I tried a lot of things, but they all went wrong

This is not very specific. It is a lot easier to help when I know what your goal is. These commands are mainly meant to be used in template definitions. Actually _all_ commands written in CamelCase are…

**Comment by cgnieder** [comment]
I close this due to missing feedback.
