### ISSUE TITLE
Ignore or ingore?

### ISSUE THREAD

**Issue by GardnerZhao** [cgnieder/xsim#37]
@cgnieder 
Hello professor.
When I was studying the manual in the Section7.4 on page 16&17.
In the above example on page 16 , Command `\xsimsetup{tags/ingore-untagged=false}` use  "ingore".
![qq 20180628104124](https://user-images.githubusercontent.com/40025928/42010135-d8394908-7abf-11e8-91e6-81cd230203cf.png)

However, "ignore" is used in the introduction of option `tags/ignore-untagged = true|false`and`topics/ignore-untagged = true|false` on page 17.
![qq 20180628104045](https://user-images.githubusercontent.com/40025928/42010141-dc22df48-7abf-11e8-8c2c-4eb562980276.png)

But "ingore" is not in English.The n and g in the word "ignore" are inverted.
The correct word is "ignore", but the correct compilation can be made using "ingore" in the macro package.
Ignore or ingore?

In addition,I am a user is trying to study this macro package, but almost no one around me to learn or use this macro package, so I am in the process of learning to produce a lot of confusion, but I sometimes don't solve these questions, so only here to ask you for help. And my English is not high, so some  sentences or grammar is not smooth, hope your understanding. Hope get your more help and guidance. Thank you very much.

My MWE.
```
\documentclass{article}
\usepackage{xsim}

\ProvideExerciseTagging{tags}
\ProvideExerciseTagging{topics}
\DeclareExerciseTagging{diff}
\xsimsetup{%
	diff={easy,medium}
}
\xsimsetup{%
	tags/ingore-untagged=true ,
	            %If <ingore> is used correctly, <ignore> is used incorrectly
	topics/ingore-untagged=true%
}
\begin{document}
%1
\begin{exercise}[diff=easy,tags=A01]
My exercise1
\end{exercise}
\begin{solution}
My Answer1
\end{solution}
%2
\begin{exercise}[diff=medium,tags=A02]
	My exercise2
\end{exercise}
\begin{solution}
	My Answer2
\end{solution}
%3
\begin{exercise}[tags=A02 ,topics=AAA]
	My exercise3
\end{exercise}
\begin{solution}
	My Answer3
\end{solution}
\end{document}
```

**Comment by cgnieder** [comment]
Thank you very much! I'll correct this for the next release.
