### ISSUE TITLE
make \TotalExerciseGoal (and other commands) expandable

### ISSUE THREAD

**Issue by maphy-psd** [cgnieder/xsim#38]
Make `\TotalExerciseGoal[s]` and maybe `\TotalExerciseTypeGoal[s]` expandable to use the number in other commands. See [here](https://tex.stackexchange.com/a/442452/41901).

For instance I calculate percentages of different goals of the total sum of the points.

Thanks! (also for this package)

**Comment by cgnieder** [comment]
Can you explain

> For instance I calculate percentages of different goals of the total sum of the points.

**Comment by cgnieder** [comment]
The thing is: it might be easier to a different command for your purpose than making `TotalExerciseGoal` expandable…

**Comment by cgnieder** [comment]
I close this until I get more feedback.
