### ISSUE TITLE
First line printed outside of environment

### ISSUE THREAD

**Issue by noctux** [cgnieder/xsim#44]
Hello, thank you for the package!

I'm currently porting our exercises from exsheets to xsim, and noticed a strange behaviour. Up to now, we used the following structure for crossreferencing:

```latex
\begin{exTask}[name=Verarbeitung]\label{checksum}
...
\end{exTask}
```

However, with xsim, the label is not correctly set afterwards. However, it works when the `\label` command is placed on a new line. The problem seems to be that any content that is on the same line as the start of the environment is acutally emitted before the environment is started.

MWE:
```latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[ngerman]{babel}

\usepackage{xsim,lipsum,xcolor}

\begin{document}

\begin{exercise}[subtitle=lipsum] ASDF
	\lipsum[1]
\end{exercise}

\end{document}
```

Output:
![2019-04-01-123525_662x350_scrot](https://user-images.githubusercontent.com/291559/55321734-aacfd000-547a-11e9-88d5-ce243b305413.png)

Thank your for your effort!

**Comment by cgnieder** [comment]
This is because the inside of an exercise is written to an external file. The reading mechanism cannot cope with stuff that is on the same line as `\begin{exercise}`. I am afraid I can't change this behaviour

**Comment by cgnieder** [comment]
This is actually mentioned in the manual but I will emphasize it in the next release!

**Comment by noctux** [comment]
Thank you for the explanation and for looking into it!
