### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by anhtuanvcu** [cgnieder/xsim#5]
Hi!
In compile error file examples of xsim  v0.5 and v0.6 error
![xsim](https://cloud.githubusercontent.com/assets/28522563/25790077/05d86560-33e0-11e7-9152-28fdd8ab55e8.png)
Please check for me!
I am using Texlive 2016 with editor Texstudio
Thank!

**Comment by cgnieder** [comment]
When you have an error please *always* show the (first) error message from the log file and also give more details of which examples you tried. I managed to figure out from the attached picture that you compiled `boxed-headings.tex` which compiles fine and without errors or even warnings on my system (up to date TL16 ).
