### ISSUE TITLE
Use the filehook package instead of scrlfile

### ISSUE THREAD

**Issue by pablgonz** [cgnieder/xsim#50]
Hello, the following file does not compile after updating TeXLive today:
```tex
\documentclass{article}
\usepackage{xsim}
\usepackage{unicode-math}
\begin{document}
$a+b$
\end{document}
```
show
```
Package filehook Warning: Macro \InputIfFileExists got redefined after 'filehoo
k' was loaded.
Certain file hooks might now be dysfunctional! on input line 4.
```
This is related to another of your packages (https://tex.stackexchange.com/q/512189/7832). Any particular reason not to use the package directly  `filehook` package?.
Saludos

**Comment by cgnieder** [comment]
This is most likely an issue of the `filehook` package. The new LaTeX kernel (2019.10.16) changed the definition of `\InputIfFileExists` and `scrlfile` (scrlfile 2019/10/12 v3.27) adapted its definitions accordingly. `filehook-scrlfile` is still 2011/01/03 v0.1 and hasn't adapted its definitions. Since `filehook` seems to be actively maintained (the current version is 2019/10/03 v0.6) this should rather be addressed there…

**Comment by pablgonz** [comment]
A thousand apologies, when I wrote this had not been updated `scrlfile` :)

**Comment by cgnieder** [comment]
I believe you misunderstood me. There is an error with an up to date system. But the fix should be made in the `filehook` package and not in `xsim`.

**Comment by pablgonz** [comment]
Now I understand you, anyway you are right, I expressed myself wrongly, is a problem of the package `filehook`, the strange thing is that I get the message only when using `unicode-math`, in my mind I believed that `xsim` only used `l3` packages and not law nor I noticed before I loaded `scrlfile` with which I am not very familiar (I have never used KOMA). 
As a closing comment, it's not a good idea to reinvent the wheel, but, you can avoid using `scrlfile` using only `expl3`?
Thank you for taking the time to respond.

**Comment by pablgonz** [comment]
[latex will change definition of `\InputIfFileExists` and this breaks  filehook](https://bitbucket.org/martin_scharrer/filehook/issues/1/latex-will-change-definition-of)
