### ISSUE TITLE
A simple grid and oval 

### ISSUE THREAD

**Issue by pablgonz** [cgnieder/xsim#52]
Hi Clemens, you could add a grid and oval (using l3draw :), something like this:

![salida](https://user-images.githubusercontent.com/2289461/67419976-18248900-f5a4-11e9-9feb-8b3b6a3f9f00.png)
Useful for writing high school exams.
```tex
\documentclass{article}
\usepackage{l3draw}
\begin{document}
\ExplSyntaxOn
% grid
\draw_begin:
\draw_linewidth:n { 0.5pt }
\draw_color:n { yellow!80!black } % OK
\draw_path_grid:nnnn
{ 0.5cm } { 0.5cm } { 0cm , 0cm } { \linewidth , 2cm }
\draw_path_use_clear:n { stroke }
\draw_end:
\ExplSyntaxOff
\par
\ExplSyntaxOn
% oval
\draw_begin:
\draw_path_corner_arc:nn { 1mm } { 1mm }
\draw_path_rectangle_corners:nn
{ 0cm , 0cm } { \linewidth , 2cm }
\draw_path_use_clear:n { stroke }
\draw_end:
\ExplSyntaxOff
\end{document}
```
Saludos

**Comment by cgnieder** [comment]
Just a comment: as long as l3draw is considered experimental I won't use it in any of my packages.

I would recommend defining your own xsim style (there is a section about them in the manual).
