### ISSUE TITLE
Problem with \SetExpandedExerciseProperty{points}

### ISSUE THREAD

**Issue by infomobi** [cgnieder/xsim#58]
Hello,

I have a problem with the latest version of xsim 0.18.
At some point, I use
`\SetExpandedExerciseProperty{points}{\theexpoints}`
multiple times in an exercise to generate "Teilleistungen" as subparts of solutions with individual points that are summed up to the exercise points at the end of the exercise.
Maybe this solution is not the best or easiest way to achive this, but it worked fine up to version 0.16.
Today I updated to 0.18 and it doesn´t work anymore. The exercise points sum is always 0.
After the downgrade to 0.16 it works again. I didn´t check 0.17.

Is this an error or is my workaround to implement "Teilleistungen" not supported any more?

Thanks,
Mirko

**Comment by cgnieder** [comment]
The way points are recorded by `xsim` has changed in v0.17. Before that version this MWE
```latex
\documentclass{article}
\usepackage{xsim}

\begin{document}

\begin{exercise}[points=2]
  \addpoints{4}
\end{exercise}

\printtotalpoints

\end{document}
```

printed

![image](https://user-images.githubusercontent.com/2248538/75269278-f1e45380-57f8-11ea-9432-ae72b0af44c8.png)

Now it prints

![image](https://user-images.githubusercontent.com/2248538/75269353-104a4f00-57f9-11ea-93be-707d57739e19.png)

My guess is that you don't need your construction any more…

**Comment by infomobi** [comment]
Oh yes, that solved my problem.

Thanks for your great work!
