### ISSUE TITLE
! LaTeX Error: File `translations.sty' not found.

### ISSUE THREAD

**Issue by kamar535** [cgnieder/xsim#59]
I'm trying to install xsim and build an old LaTex/xsim project on a new macOS machine.  The machine I used to originally build the project is dead and I don't remember exactly which version of xsim I used when building the project originally. 

I don't have much experience installing and updating LaTex packages. I used tlmgr to install xsim. 

```
tlmgr install xsim
```

When i compile the project I get the following error: 

```
! LaTeX Error: File `translations.sty' not found.
```

According to the the .log file:

```
Package: xsim 2020/02/23 v0.18 eXercise Sheets IMproved
```

At the end of the log: 

```
Package xsim Info: Loading module `translations' ...


(/usr/local/texlive/2019basic/texmf-dist/tex/latex/xsim/xsim.translations.code.
tex
File: xsim.translations.code.tex 2020/02/23 v0.18 xsim module `translations' (l
anguage settings for XSIM)


! LaTeX Error: File `translations.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Emergency stop.
<read *>

l.32 \msg_new:nnn
                  {xsim} {language-not-defined}
End of file on the terminal!
```

Could the problem be that I need to revert back to an old version of xsim?  If so, how do I do this?

Any suggestions on how to resolve this issue are welcome.

**Comment by cgnieder** [comment]
The first version of the `translations` package dates back to 2012 and was added to CTAN and the major distributions in 2013. So you either have a very outdated TeX distribution (TeX live, MiKTeX, …) or more likely an incomplete one…

BTW: `xsim` used `translations` from the very beginning…

**Comment by kamar535** [comment]
Thank you @cgnieder!

On my old machine I must have hade the translations package installed. 

I have a poor understanding of the LaTeX package system and assumed the translation.sty was part of the  xsim  package. 

After installing the translations package on my new machine using tlmgr I could compile again. 

Btw,  is there a way for LaTeX packages to declare dependencies so that tools like tlmgr automatically can download all dependencies?

**Comment by cgnieder** [comment]
Not that I know of. Given that most computers have loads of gigabytes disk space nowadays the easiest thing usually just is to install the complete scheme.

**Comment by pablgonz** [comment]
@kamar535 You can do something (more less) using [texliveonfly](https://tex.stackexchange.com/a/463842) and some help from the `snapshot` package:

```
pdflatex -draftmode -interaction=batchmode "\RequirePackage{snapshot}\input{main}" 
```
and a little bit of perl :)

```perl
perl -wnE 'say $1 if /(?:\*\{p.+?\}\s*)\{(.+?)\}(?:\s*\{.+?\})/' snapshot.dep
```

**Comment by cgnieder** [comment]
This appears to be solved, yes?
