### ISSUE TITLE
`xsim` needs `xparse` 2017-03-07 or newer

### ISSUE THREAD

**Issue by ericguirbal** [cgnieder/xsim#6]
The package `xsim` uses the macro `NewExpandableDocumentCommand` added in the 2017-03-07 release of `xparse`. What about an error message to inform the users when `xparse` is too old ?

**Comment by cgnieder** [comment]
But this `xparse` release is *older* than `xsim`!

**Comment by cgnieder** [comment]
What I meant to say is this: it is not unreasonable to assume for a package author that users have an up to date TeX distribution.

**Comment by cgnieder** [comment]
The manual already has this in section 1 *Licence, Requirements and readme*:

> xsim loads the packages expl3 [L3Pa], xparse [L3Pb], etoolbox [Leh15], array [MC08]
> booktabs [Fea05] and translations [Nie15]. All of these packages are present on a modern and
> up to date TeX distribution such as TeX Live or MiKTeX so no further action should be needed.
> When you are using xsim you should be using an up to date TeX distribution, anyway.
> 
> Newer versions of xsim may depend on newer versions of the support packages.
> Remember: it is always dangerous to update single packages. Always update your TeX
> distribution if you want an up to date version of a package. Be careful: if you’re in the
> middle of an important project it might be better to wait with the update until you’ve
> finished the project. Every update might be breaking some things.
>
