### ISSUE TITLE
issues when using xsim on Overleaf

### ISSUE THREAD

**Issue by cniallen** [cgnieder/xsim#61]
I am just getting acquainted with your wonderful xsim package, but I am pretty certain an issue arise when I use it online with Overleaf as I get the following warning:

> Package xsim Warning: You are trying to load the template `runin' (template type `begin') on line 153. This template does not seem to be defined. I am using the template `default' (template type `begin') instead.

In addition to loading the package in the preamble, I wrote: 

> \xsimsetup{
    exercise/print=true,
    solution/print=false
}
\SetExerciseParameters{exercise}{
    exercise-template = runin,
    solution-template = runin
}

Did I forget something?

**Comment by cgnieder** [comment]
First of all please keep in mind that the version of `xsim` on Overleaf is not the newest version. Currently they have v0.16 (https://github.com/cgnieder/xsim/releases/tag/v0.16).

In order to use the additional layouts you need to load the `xsim`-style `layouts` first:

```latex
\documentclass{article}

\usepackage[no-files]{xsim}
\xsimsetup{
  load-style=layouts , % <<<<<<
  exercise/template=runin
}

\begin{document}

\begin{exercise}
  Some text
\end{exercise}

\end{document}
```
