### ISSUE TITLE
Making my own template on Overleaf

### ISSUE THREAD

**Issue by cniallen** [cgnieder/xsim#62]
Creating my own template with \DeclareExerciseEnvironmentTemplate also seems problematic on Overleaf.

**Comment by cgnieder** [comment]
**First of all please keep in mind that the version of `xsim` on Overleaf is not the newest version. Currently they have v0.16 (https://github.com/cgnieder/xsim/releases/tag/v0.16).**

--------

Works for me: https://www.overleaf.com/read/qhqtgwchhymm
