### ISSUE TITLE
How to reproduce xsim's documentation

### ISSUE THREAD

**Issue by pablgonz** [cgnieder/xsim#63]
Hi, I'm trying to repoduce xsim's documentation with the available files, but I haven't succeeded, I get the error:

```
! LaTeX Error: File `libertinehologopatch.sty' not found.
```
along with others. 

Can you point me in the right direction?
Saludos

**Comment by cgnieder** [comment]
You can download it here: https://github.com/cgnieder/libertinehologopatch

**Comment by pablgonz** [comment]
@cgnieder Thanks for the link, one question, if I remember correctly TeXLive's policy is to provide the necessary files to regenerate the documentation, but, `libertinehologopatch.sty` is not part of TeXLive nor is it in CTAN, I am right?

**Comment by pablgonz** [comment]
@cgnieder Mmmm
```
! LaTeX Error: Command \xsimman@readoptions already defined.
               Or name \end... illegal, see p.192 of the manual.
```

**Comment by cgnieder** [comment]
> @cgnieder Mmmm
> 
> ```
> ! LaTeX Error: Command \xsimman@readoptions already defined.
>                Or name \end... illegal, see p.192 of the manual.
> ```

I know, a bug in `xsim-manual.cls` which I've overlooked. I've already fixed it locally. Use the one from the next commit :)

**Comment by cgnieder** [comment]
> @cgnieder Thanks for the link, one question, if I remember correctly TeXLive's policy is to provide the necessary files to regenerate the documentation, but, `libertinehologopatch.sty` is not part of TeXLive nor is it in CTAN, I am right?

It is neither on CTAN nor part of texlive. But texlive only requires that the source for documentation is included: https://tug.org/texlive/pkgcontrib.html

**Comment by pablgonz** [comment]
@cgnieder Okay, maybe you could include "Libertinehologopatch.sty" inside "cltx-doc"... I was actually playing around with `l3build` in order to create a local installation of `xsim` (which works), I just got stuck in the generation of the documentation.

**Comment by cgnieder** [comment]
> > @cgnieder Mmmm
> > ```
> > ! LaTeX Error: Command \xsimman@readoptions already defined.
> >                Or name \end... illegal, see p.192 of the manual.
> > ```
> 
> I know, a bug in `xsim-manual.cls` which I've overlooked. I've already fixed it locally. Use the one from the next commit :)

cbf26b91f60024f121c68afa8d6fd6ac22993cba

**Comment by pablgonz** [comment]
@cgnieder 
```
[pablo@worktex tempgit] $ git clone https://github.com/cgnieder/xsim.git
Clonando en 'xsim'...
remote: Enumerating objects: 348, done.
remote: Counting objects: 100% (348/348), done.
remote: Compressing objects: 100% (247/247), done.
remote: Total 1382 (delta 246), reused 199 (delta 101), pack-reused 1034
Recibiendo objetos: 100% (1382/1382), 17.39 MiB | 3.98 MiB/s, listo.
Resolviendo deltas: 100% (981/981), listo.
[pablo@worktex tempgit] $ cd xsim/
[pablo@worktex xsim] $ ls
code  doc  README
[pablo@worktex xsim] $ cd doc/
[pablo@worktex doc] $ wget https://github.com/cgnieder/libertinehologopatch/blob/master/libertinehologopatch.sty
--2020-03-17 14:32:30--  https://github.com/cgnieder/libertinehologopatch/blob/master/libertinehologopatch.sty
Resolviendo github.com (github.com)... 18.228.67.229
Conectando con github.com (github.com)[18.228.67.229]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: no especificado [text/html]
Grabando a: “libertinehologopatch.sty”

libertinehologopatc     [  <=>               ] 189,90K   805KB/s    en 0,2s    

2020-03-17 14:32:32 (805 KB/s) - “libertinehologopatch.sty” guardado [194458]

[pablo@worktex doc] $ ls
examples                  xsim.history  xsim-manual.cls  xsim_manual.tex
libertinehologopatch.sty  xsim.ideas    xsim_manual.pdf
[pablo@worktex doc] $ arara xsim_manual.tex 
  __ _ _ __ __ _ _ __ __ _
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing 'xsim_manual.tex' (size: 105.5 kB, last modified:
03/17/2020 14:31:39), please wait.

(PDFLaTeX) PDFLaTeX engine .............................. FAILURE

Total: 2.20 seconds
```

**Comment by cgnieder** [comment]
Well, the error message is rather clear, isn't it: you obviously don't have created a folder named `exercises`.

----

The class file has

```latex
\xsimsetup{
  % clear-aux ,
  path = exercises
}
```

which is mentioned in the manual:

```latex
  \keyval{path}{path name}\Default
    With this option a subfolder or path within the main project folder can be
    given.  Exercises will be written to and included from this path.
    \emph{The path must exist on your system before you can use it!} This
    document uses \keyis{path}{exercises}.
```

**Comment by pablgonz** [comment]
@cgnieder Now that's the last thing I'm bothering you with. The documentation for version 0.19 compiles perfectly, but, with version 0.18 installed on my system (TeXLive 2020), copying the files from `/code` to `/doc` generates the following error:

```tex
Package: xsim 2020/03/16 v0.19 eXercise Sheets IMproved

(./xsim.modules.code.tex)

Package xsim Info: Loading module `definitions' ...

 (./xsim.definitions.code.tex
! Undefined control sequence.
\__xsim_module:nn ..._prop {#1}{#2}\str_if_eq:xxF 
                                                  {\c__xsim_module_prefix_tl...
l.28 ...{definitions}{definition of user commands}
                                                  
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.


! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                         
```

I'm attaching the log files:

[xsim_manual_OK.log](https://github.com/cgnieder/xsim/files/4346394/xsim_manual_OK.log)
[xsim_manual.log](https://github.com/cgnieder/xsim/files/4346395/xsim_manual.log)

**Comment by cgnieder** [comment]
That's a newly introduced bug – I don't see how I can have overlooked this :(

For the time being use

```latex
\usepackage{expl3}
\ExplSyntaxOn
\cs_generate_variant:Nn \str_if_eq:nnF {xx}
\ExplSyntaxOff
\usepackage{xsim}
```
