### ISSUE TITLE
Add xsim to l3prefixes

### ISSUE THREAD

**Issue by pablgonz** [cgnieder/xsim#69]
Hi, could you add your packages to  latex3/l3kernel/doc/l3prefixes.csv.
Here's a link:

https://github.com/latex3/latex3/blob/master/l3kernel/doc/l3prefixes.csv

That file is for contact info, but also to keep track of the registered prefixes in packages to avoid that two packages use the same prefix and clash.

Greetings
Pablo

**Comment by cgnieder** [comment]
Thanks. I had forgotten about that list. I created a pull request.
