### ISSUE TITLE
Use standard warning message

### ISSUE THREAD

**Issue by giordano** [cgnieder/xsim#7]
It's nice that `xsim` emits a warning when the user needs to rerun latex, but would be even better if the message followed the standard (message starting the line exactly with: `Package xsim Warning:`), so that editors can easily catch the message.  `\PackageWarning` macro would work.

Having to deal with custom message for each single package isn't particularly fun :-)

**Comment by cgnieder** [comment]
`xsim` is completely written in expl3 and the messages *do* follow the l3 standard. Quoting the [L3 interfaces](http://mirrors.ctan.org/macros/latex/contrib/l3kernel/interface3.pdf):

> Messages need to be passed to the user by modules, either when errors occur or to indicate
> how the code is proceeding. The l3msg module provides a consistent method for doing
> this (as opposed to writing directly to the terminal or log).
> The system used by l3msg to create messages divides the process into two distinct
> parts. Named messages are created in the first part of the process; at this stage, no
> decision is made about the type of output that the message will produce. The second
> part of the process is actually producing a message. At this stage a choice of message
> *class* has to be made, for example `error`, `warning` or `info`.
> By separating out the creation and use of messages, several benefits are available.
> First, the messages can be altered later without needing details of where they are used
> in the code. This makes it possible to alter the language used, the detail level and so
> on. Secondly, the output which results from a given message can be altered. This can be
> done on a message class, module or message name basis. In this way, message behaviour
> can be altered and messages can be entirely suppressed.

The message is defined by

```latex
\msg_new:nnn {xsim} {rerun}
  {
    Exercise~ properties~ may~ have~ changed.~ Rerun~ to~ get~ them~
    synchronized.
  }
```

and is the invoked by `\msg_warning:nn {xsim} {rerun}` which outputs

```
*************************************************
* xsim warning: "rerun"
* 
* Exercise properties may have changed. Rerun to get them synchronized.
*************************************************
```

in the log. One could redefine the l3msg macro `\msg_warning_text:n {<module>}` which is responsible for the output `<module> warning` and change it to output `Package <module> warning` (and for the sake of consistency also `\msg_info_text:n`, `\msg_error_text:n`, `\msg_fatal_text:n`, and \msg_critical_text:n). I am not yet convinced I should do this or switch to 2e just for the one warning…

Wouldn't it be better for editors which are keen on spotting theses massages to also recognize the expl3/l3msg “standard”? Given that the number of packages using it is growing…

**Comment by giordano** [comment]
> Wouldn't it be better for editors which are keen on spotting theses massages to also recognize the expl3/l3msg “standard”? Given that the number of packages using it is growing…

I was asked to catch this warning in AUCTeX, and looks like this is the first package we're going to support that uses expl3 framework.

So, all warnings stars with
```
* <package-name> warning:
```
right?  If this is the standard message, it's easy to accommodate.

**Comment by cgnieder** [comment]
The MWE

```latex
\documentclass{article}
\usepackage{expl3}

\ExplSyntaxOn
\msg_new:nnn {foo} {message-name} {message~ text}
\ExplSyntaxOff

\begin{document}

\ExplSyntaxOn
\msg_info:nn {foo} {message-name}
\msg_warning:nn {foo} {message-name}
\msg_error:nn {foo} {message-name}
\ExplSyntaxOff

\end{document}
```

gives in the log

```
.................................................
. foo info: "message-name"
. 
. message text
.................................................
```

```
*************************************************
* foo warning: "message-name"
* 
* message text
*************************************************
```

and

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! foo error: "message-name"
! 
! message text
! 
! See the foo documentation for further information.
! 
! Type <return> to continue.
!...............................................  
```

So yes: warnings all start with `* <package-name> warning:`

**Comment by giordano** [comment]
Ok, done with commit https://git.savannah.gnu.org/gitweb/?p=auctex.git;a=commitdiff;h=0c03e4ac6042e7c19e4202b6d95c8c515145d264 (https://github.com/giordano/auctex/commit/0c03e4ac6042e7c19e4202b6d95c8c515145d264).  Thanks!
