### ISSUE TITLE
Doc: \expandable overlaps with the backslash

### ISSUE THREAD

**Issue by muzimuzhi** [cgnieder/xsim#74]
Currently, the star created by `\expandable` overlaps with the backslash created by `\command`.
https://github.com/cgnieder/xsim/blob/d3f8667b40878ffadfc317d46b94bf4623eb2690/doc/xsim-manual.tex#L1388-L1391
![image](https://user-images.githubusercontent.com/6376638/103509440-1c358180-4e9e-11eb-95bb-21644a78262e.png)

If this effect is not intented, then perhaps moving `\expandable` a bit left is better.

**Comment by cgnieder** [comment]
Thanks for the report. The document would have needed (at least) one more compilation run to place the star correctly.
I'll try to do better next time :)

**Comment by muzimuzhi** [comment]
I compiled `xsim-manual.tex` for ten times and the problem is not auto fixed. Perhaps the problem requires a deeper investigation.

Meanwhile, more minor problems were spotted during manual compilation:
 - The filename `xsim-manual.tex` uses dash character `-`, but it tries to load an aux file assuming underscore `_` is used:
    https://github.com/cgnieder/xsim/blob/4a1bc05e56fc97ca556df916a2ee479b08064ed0/doc/xsim-manual.tex#L287-L290
    https://github.com/cgnieder/xsim/blob/4a1bc05e56fc97ca556df916a2ee479b08064ed0/doc/xsim-manual.tex#L304
 - Three examples are not found the repository: `xsim.texsx-466584.tex`, `xsim.texsx-576998.tex`, and `xsim.issues-49.tex`.

**Comment by cgnieder** [comment]
> I compiled `xsim-manual.tex` for ten times and the problem is not auto fixed. Perhaps the problem requires a deeper investigation.

No, it doesn't. The publicly available sources just are not up to date. Believe me, this is fixed :)

> 
> Meanwhile, more minor problems were spotted during manual compilation:
> 
>     * The filename `xsim-manual.tex` uses dash character `-`, but it tries to load an aux file assuming underscore `_` is used:
>       https://github.com/cgnieder/xsim/blob/4a1bc05e56fc97ca556df916a2ee479b08064ed0/doc/xsim-manual.tex#L287-L290
>       
>       https://github.com/cgnieder/xsim/blob/4a1bc05e56fc97ca556df916a2ee479b08064ed0/doc/xsim-manual.tex#L304
> 
Typos, fixed, thanks.

>     * Three examples are not found in the repository: `xsim.texsx-466584.tex`, `xsim.texsx-576998.tex`, and `xsim.issues-49.tex`.

Added, thanks.

**Comment by cgnieder** [comment]
Actually we're both right :D the problem in the xsim manual is that the marginparsep is too small. The star is correctly placed but has no space…

```latex
\documentclass{cnltx-doc}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\geometry{
  left = 3.5cm ,
  right = 3cm ,
  marginparwidth = 3cm ,
  marginparsep = 2mm % change to 4mm for example
}

\begin{document}

\begin{commands}
  \expandable\command{foo}[\marg{bar}]
    Bla bla
\end{commands}

\end{document}
```

**Comment by muzimuzhi** [comment]
Another case in which `geometry` option `showframe` is helpful. :)

Thanks for digging into this. I have found the definition of `\expandable` in `cnltx-doc.cls` before opened this issue, but was too lazy to either reduce the example or read and understand the code.
