### ISSUE TITLE
Comments are shown in the document

### ISSUE THREAD

**Issue by giordano** [cgnieder/xsim#8]
```latex
\documentclass{article}
\usepackage{xsim}
\begin{document}
\begin{exercise}[points=50] % hello world
\end{exercise}
\end{document}
```
The commented line `% hello world` is shown in the output document.

**Comment by cgnieder** [comment]
That is the same behaviour that the `filecontents` environment shows:

```latex
\documentclass{article}
\usepackage{filecontents}
\begin{document}
\begin{filecontents}{foo} % hello world
\end{filecontents}
\end{document}
```

I admit I haven't documented the behaviour but I don't see any way around it. That's just how it is: *you can't use the rest of the first line* (I wouldn't even place a `\label` there or anything…) Just use the next line

```latex
\documentclass{article}
\usepackage{xsim}
\begin{document}
\begin{exercise}[points=50]
  % hello world
\end{exercise}
\end{document}
```

**Comment by giordano** [comment]
Ok, can this be at least documented?

**Comment by cgnieder** [comment]
Yes, I will add something to the manual.

**Comment by ChristopherChudzicki** [comment]
I know this is closed, but I've just noticed that this behavior only happens when optional arguments are passed to `exercise`. That is,

```
\documentclass{article}
\usepackage{xsim}
\begin{document}
\begin{exercise} % hello world
\end{exercise}
\end{document}
```
does not show the comment.

**Comment by cgnieder** [comment]
Yes, the different behavior is due to the fact that TeX needs to scan ahead for a `[` in order to find the optional argument. It doesn't need to when it already found the optional argument.
