### ISSUE TITLE
Unexpected side effect of new version V0.20c

### ISSUE THREAD

**Issue by marvinmarvin** [cgnieder/xsim#82]
With the attached minimal example I am used to get **Exercise 1** _Version B_, but with the new version I get **Exercise 2** _Version B_ – obviously Version A is counted but – as expected – not shown.  
What is the reason for this change in behaviour? – And how to get back the old behaviour?

```latex
\documentclass[fontsize=12pt,paper=a4]{scrartcl}
% 
\usepackage{iftex}
\ifluatex
\RequirePackage{unicode-math}
\else
\usepackage[T1]{fontenc}    
\fi



\usepackage{xsim}

\DeclareExerciseTagging{Version}

\xsimsetup{Version=Zwei}

\begin{document}
\begin{exercise}[subtitle={Version A},points=10,Version={Eins}]
  Solve first exercise  
\end{exercise}
\begin{solution}
  solution 1
\end{solution}

\begin{exercise}[subtitle={Version B},points=10,Version={Zwei}]
  Solve second exercise  
\end{exercise}
\begin{solution}
  solution 2
\end{solution}
\end{document}
```

**Comment by cgnieder** [comment]
The next version will again default to your expected behavior, with an option to change to the current one on a per-tag basis
