### ISSUE TITLE
commands in setup

### ISSUE THREAD

**Issue by blacheref** [cgnieder/xsim#86]
Hi,
Does it exist a way to use commands in `\xsimsetup` ? I would like to achieve things like presented in the following code, because I reuse the `\semester` commands in other places.
```
\newcommand{\semester}{202109}
\newcommand{\printSolutions}{true}
\xsimsetup{
    solution/print = \PrintSolutions,
    tags={\semester},
}
```
Thanks by advance.

**Comment by muzimuzhi** [comment]
You can try fully expanding the key-val list before passing it to `\xsimsetup`.

```tex
\documentclass{article}
\usepackage{xsim}

\newcommand{\semester}{202109}
\newcommand{\PrintSolutions}{true}

\expandafter\xsimsetup\expanded{{
  solution/print = \PrintSolutions,
  tags={\semester},
}}

\begin{document}
content
\end{document}
```

**Comment by blacheref** [comment]
This is working nicely, thanks !

**Comment by muzimuzhi** [comment]
Be careful that not every key-val pair (mostly the value) is fully expandable. So you might need to write two `\xsimsetup`s.
