### ISSUE TITLE
Lstlistings in exercise-environment broken

### ISSUE THREAD

**Issue by infomobi** [cgnieder/xsim#87]
Hello,

the current published version of xsim in the Mactex-distribution broke my documents where I use lstlistings in exercise environment. Is this a known bug? When will it be fixed?

Latexcode
```
\begin{document}
	Before exercise
\begin{exercise}
	before listing
\begin{lstlisting}
	in listing
\end{lstlisting}
	after listing
\end{exercise}
	after exercise
\end{document}
```

Error message is
`./DeleteMe.tex:37: LaTeX Error: \begin{lstlisting} on input line 37 ended by \end{addmargin}.`

Thanks for your work!

**Comment by muzimuzhi** [comment]
`xsim` v0.20, 2021/01/31 [made package option `no-files' the default](https://github.com/cgnieder/xsim/blob/f0026818378558a91000c3b606f3cbf88c5e6db0/HISTORY#L176), which will

> prevent using verbatim material in exercises and solutions.
> _[doc of `xsim`, sec. 3.2]_

Solution: use package option `use-files`.

**Comment by muzimuzhi** [comment]
Note that

> ... `xsim` is in an experimental state and actively developed. Many aspects may change from one update to another until a stable version 1 will be reached. However, I will try my best to keep the interface stable.
> _[doc of `xsim`, sec. 1]_

**Comment by infomobi** [comment]
Thanks a lot.
Didn't recognize that.
