### ISSUE TITLE
Use rerunfilecheck to ensure that exercise information is up to date

### ISSUE THREAD

**Issue by N-Coder** [cgnieder/xsim#88]
When making structural changes to the exercise of a document (e.g. adding and removing or reordering), `xsim` sometimes doesn't pick up all the changes and keeps outdated information, leading to wrong information in the output file - even when using `clear-aux` (which according to docs only checks the number of exercises).
My recommendation would be to use the [rerunfilecheck](https://ctan.net/macros/latex/contrib/rerunfilecheck/rerunfilecheck.pdf) package to see if the MD5 hash of the `document.xsim` cache changed and only clear and rerun depending on this information.
The package only works with pdf- and luatex, but that should cover most of the uses.

**Comment by muzimuzhi** [comment]
XeTeX has added primitive `\mdfivesum` [in 2016](https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-830009.1.13), and latex3 has provided engine-independent functions `\file_mdfive_hash:n` and `\file_get_mdfive_hash:nNTF`. So it's possible for `xsim` to do the MD5 check that works on all the common engines, by itself.

**Comment by cgnieder** [comment]
I implemented the md5 check for the next version.
