### ISSUE TITLE
\printsolutions does not work if the option "-output-directory" is used

### ISSUE THREAD

**Issue by mschneiderwng** [cgnieder/xsim#93]
The following command produces exercises and solutions.
`lualatex -synctex=1 -interaction=nonstopmode test.tex`
The following command creates a pdf with exercises only.
`lualatex -synctex=1 -interaction=nonstopmode -output-directory=result test.tex`

The test.tex used contains
```
\documentclass[]{article}
\usepackage{xsim}
\begin{document}
  \begin{exercise}
  	\(x - 1 = 0\)
  \end{exercise}
  \begin{solution}
  	\(x = 1\)
  \end{solution}
  \printsolutions
\end{document}
```

**Comment by cgnieder** [comment]
The reason is the usage of the auxiliary file `.xsim`. Use
```latex
\usepackage[use-aux]{xsim}
```
to prevent the issue.

**Comment by mschneiderwng** [comment]
That solves the problem. Thank you for your fast response and this awesome package.
