### ISSUE TITLE
Example file xsim.issue-49.tex does not produce expected output

### ISSUE THREAD

**Issue by wwywong** [cgnieder/xsim#96]
The file [xsim.issue-49.tex](https://github.com/cgnieder/xsim/blob/0eb5d4301b358b85b46947619067a51d1af53068/doc/examples/xsim.issues-49.tex) does not produce the output included in the repository. Exercises 6, 7, and 8 have repeated choice labels. (See also https://tex.stackexchange.com/q/630848/119 )

Built using:
````
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2021/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./xsimtest2.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2021-11-22>
````

xsim version: `Package: xsim 2021/02/03 v0.20c eXercise Sheets IMproved`
tasks version: `Package: tasks 2021/02/20 v1.3a lists with columns filled horizontally`

**Comment by wwywong** [comment]
I am guessing this is broken by some change to the `tasks` package. 

Replacing the definition of `\correct` to add `\refstepcounter` seems to fix the problem. 

```
\newcommand*\correct{\refstepcounter{task}\thetask\expanded{\SetExerciseProperty{choice}{\thetask}}}
```

**Comment by muzimuzhi** [comment]
The change came from a fixed problem in `tasks`. According to cgnieder/tasks#24, the `\refstepcounter` _is_ now required since  `tasks` v1.4 (2022/01/08).

**Comment by cgnieder** [comment]
Thanks. Fixed for the next release.
